### ISSUE TITLE
Cannot interact with graph view

### ISSUE THREAD

**Issue by ryanpcmcquen** [chad-bennett/al-dente-obsidian-theme#5]
Graph view is broken with this theme. You cannot move the graph, you cannot interact with nodes. You cannot zoom. I can reproduce this with the default help Vault.
![broken_graph_view_al_dente](https://user-images.githubusercontent.com/772937/121787241-d4680400-cb79-11eb-96fe-08787bfed7ff.gif)

**Comment by chad-bennett** [comment]
fixed. i don't normally use graph view, so wasn't used to this problem. 

the issue was that graph view is shown as an iframe. I have a special class made for iframes to keep them centered and responsive. that was conflicting. 

here's the class, if you want to use it. have to do it as html in your note, but it displays really well. good for embedded youtube videos.  

```
<div class="iframeDiv"><iframe src="something" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe></div>

```
